void *connection_handler(void *);
void *menu_servidor(void *);
void generar_md5sum(char*);
void generar_archivos_cantidad();
int revisar_cantidad_archivos();
void revisar_generacion_index(char*);
void directorioArchivos(char*,vector*);
void sort_strings(vector*,int);
int directorio_archivos_cantidad(char*);
void escribirBitacora(char*);
void leer_archivo_datos(char*,vector*,vector*,vector*);
void *actualizar_index(void *);
void actualizar_datos();
void cargar_archivos_vectores(void);
long int findSize(char*);
void generar_index_slideshow(char*,vector*,vector*,vector*,char*);
void generar_index(char*,vector*,vector*,vector*,char*);
int contains(vector*,char*);
int end_with_mp4(char*);